// This file is generated by kconfig_compiler_kf5 from breezesettingsdata.kcfg.
// All changes you do to this file will be lost.

#include "breezesettings.h"

using namespace Breeze;

InternalSettings::InternalSettings(  )
  : KConfigSkeleton( QLatin1String( "breezerc" ) )
{
  setCurrentGroup( QLatin1String( "Windeco" ) );

  QList<KConfigSkeleton::ItemEnum::Choice> valuesBorderSize;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderNone");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderNoSides");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderTiny");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderNormal");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderLarge");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderVeryLarge");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderHuge");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderVeryHuge");
    valuesBorderSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("BorderOversized");
    valuesBorderSize.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemBorderSize;
  itemBorderSize = new KConfigSkeleton::ItemEnum( currentGroup(), QLatin1String( "BorderSize" ), mBorderSize, valuesBorderSize, BorderNoSides );
  addItem( itemBorderSize, QLatin1String( "BorderSize" ) );
  QList<KConfigSkeleton::ItemEnum::Choice> valuesTitleAlignment;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("AlignLeft");
    valuesTitleAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("AlignCenter");
    valuesTitleAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("AlignCenterFullWidth");
    valuesTitleAlignment.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("AlignRight");
    valuesTitleAlignment.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemTitleAlignment;
  itemTitleAlignment = new KConfigSkeleton::ItemEnum( currentGroup(), QLatin1String( "TitleAlignment" ), mTitleAlignment, valuesTitleAlignment, AlignCenterFullWidth );
  addItem( itemTitleAlignment, QLatin1String( "TitleAlignment" ) );
  QList<KConfigSkeleton::ItemEnum::Choice> valuesButtonSize;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ButtonSmall");
    valuesButtonSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ButtonDefault");
    valuesButtonSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ButtonLarge");
    valuesButtonSize.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ButtonVeryLarge");
    valuesButtonSize.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemButtonSize;
  itemButtonSize = new KConfigSkeleton::ItemEnum( currentGroup(), QLatin1String( "ButtonSize" ), mButtonSize, valuesButtonSize, ButtonDefault );
  addItem( itemButtonSize, QLatin1String( "ButtonSize" ) );
  KConfigSkeleton::ItemBool  *itemDrawBorderOnMaximizedWindows;
  itemDrawBorderOnMaximizedWindows = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "DrawBorderOnMaximizedWindows" ), mDrawBorderOnMaximizedWindows, false );
  addItem( itemDrawBorderOnMaximizedWindows, QLatin1String( "DrawBorderOnMaximizedWindows" ) );
  KConfigSkeleton::ItemBool  *itemDrawSizeGrip;
  itemDrawSizeGrip = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "DrawSizeGrip" ), mDrawSizeGrip, true );
  addItem( itemDrawSizeGrip, QLatin1String( "DrawSizeGrip" ) );
  KConfigSkeleton::ItemBool  *itemAnimationsEnabled;
  itemAnimationsEnabled = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "AnimationsEnabled" ), mAnimationsEnabled, true );
  addItem( itemAnimationsEnabled, QLatin1String( "AnimationsEnabled" ) );
  KConfigSkeleton::ItemInt  *itemAnimationsDuration;
  itemAnimationsDuration = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "AnimationsDuration" ), mAnimationsDuration, 150 );
  addItem( itemAnimationsDuration, QLatin1String( "AnimationsDuration" ) );
  KConfigSkeleton::ItemBool  *itemHideTitleBar;
  itemHideTitleBar = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "HideTitleBar" ), mHideTitleBar, false );
  addItem( itemHideTitleBar, QLatin1String( "HideTitleBar" ) );
  QList<KConfigSkeleton::ItemEnum::Choice> valuesExceptionType;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ExceptionWindowClassName");
    valuesExceptionType.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QLatin1String("ExceptionWindowTitle");
    valuesExceptionType.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemExceptionType;
  itemExceptionType = new KConfigSkeleton::ItemEnum( currentGroup(), QLatin1String( "ExceptionType" ), mExceptionType, valuesExceptionType, ExceptionWindowClassName );
  addItem( itemExceptionType, QLatin1String( "ExceptionType" ) );
  KConfigSkeleton::ItemString  *itemExceptionPattern;
  itemExceptionPattern = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "ExceptionPattern" ), mExceptionPattern );
  addItem( itemExceptionPattern, QLatin1String( "ExceptionPattern" ) );
  KConfigSkeleton::ItemBool  *itemEnabled;
  itemEnabled = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "Enabled" ), mEnabled, true );
  addItem( itemEnabled, QLatin1String( "Enabled" ) );
  KConfigSkeleton::ItemInt  *itemMask;
  itemMask = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "Mask" ), mMask, 0 );
  addItem( itemMask, QLatin1String( "Mask" ) );
}

InternalSettings::~InternalSettings()
{
}

