# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kver/Development/source/breeze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kver/Development/source/breeze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"breeze\" \"kde4breeze\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/kver/Development/source/breeze && $(CMAKE_COMMAND) -E cmake_progress_start /home/kver/Development/source/breeze/CMakeFiles /home/kver/Development/source/breeze/kdecoration/CMakeFiles/progress.marks
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kver/Development/source/breeze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/kver/Development/source/breeze && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
kdecoration/CMakeFiles/breezedecoration.dir/rule:
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/CMakeFiles/breezedecoration.dir/rule
.PHONY : kdecoration/CMakeFiles/breezedecoration.dir/rule

# Convenience name for target.
breezedecoration: kdecoration/CMakeFiles/breezedecoration.dir/rule
.PHONY : breezedecoration

# fast build rule for target.
breezedecoration/fast:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/build
.PHONY : breezedecoration/fast

# Convenience name for target.
kdecoration/CMakeFiles/breezedecoration_automoc.dir/rule:
	cd /home/kver/Development/source/breeze && $(MAKE) -f CMakeFiles/Makefile2 kdecoration/CMakeFiles/breezedecoration_automoc.dir/rule
.PHONY : kdecoration/CMakeFiles/breezedecoration_automoc.dir/rule

# Convenience name for target.
breezedecoration_automoc: kdecoration/CMakeFiles/breezedecoration_automoc.dir/rule
.PHONY : breezedecoration_automoc

# fast build rule for target.
breezedecoration_automoc/fast:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration_automoc.dir/build.make kdecoration/CMakeFiles/breezedecoration_automoc.dir/build
.PHONY : breezedecoration_automoc/fast

breezebutton.o: breezebutton.cpp.o
.PHONY : breezebutton.o

# target to build an object file
breezebutton.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezebutton.cpp.o
.PHONY : breezebutton.cpp.o

breezebutton.i: breezebutton.cpp.i
.PHONY : breezebutton.i

# target to preprocess a source file
breezebutton.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezebutton.cpp.i
.PHONY : breezebutton.cpp.i

breezebutton.s: breezebutton.cpp.s
.PHONY : breezebutton.s

# target to generate assembly for a file
breezebutton.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezebutton.cpp.s
.PHONY : breezebutton.cpp.s

breezecolorsettings.o: breezecolorsettings.cpp.o
.PHONY : breezecolorsettings.o

# target to build an object file
breezecolorsettings.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezecolorsettings.cpp.o
.PHONY : breezecolorsettings.cpp.o

breezecolorsettings.i: breezecolorsettings.cpp.i
.PHONY : breezecolorsettings.i

# target to preprocess a source file
breezecolorsettings.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezecolorsettings.cpp.i
.PHONY : breezecolorsettings.cpp.i

breezecolorsettings.s: breezecolorsettings.cpp.s
.PHONY : breezecolorsettings.s

# target to generate assembly for a file
breezecolorsettings.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezecolorsettings.cpp.s
.PHONY : breezecolorsettings.cpp.s

breezedecoration.o: breezedecoration.cpp.o
.PHONY : breezedecoration.o

# target to build an object file
breezedecoration.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration.cpp.o
.PHONY : breezedecoration.cpp.o

breezedecoration.i: breezedecoration.cpp.i
.PHONY : breezedecoration.i

# target to preprocess a source file
breezedecoration.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration.cpp.i
.PHONY : breezedecoration.cpp.i

breezedecoration.s: breezedecoration.cpp.s
.PHONY : breezedecoration.s

# target to generate assembly for a file
breezedecoration.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration.cpp.s
.PHONY : breezedecoration.cpp.s

breezedecoration_automoc.o: breezedecoration_automoc.cpp.o
.PHONY : breezedecoration_automoc.o

# target to build an object file
breezedecoration_automoc.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration_automoc.cpp.o
.PHONY : breezedecoration_automoc.cpp.o

breezedecoration_automoc.i: breezedecoration_automoc.cpp.i
.PHONY : breezedecoration_automoc.i

# target to preprocess a source file
breezedecoration_automoc.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration_automoc.cpp.i
.PHONY : breezedecoration_automoc.cpp.i

breezedecoration_automoc.s: breezedecoration_automoc.cpp.s
.PHONY : breezedecoration_automoc.s

# target to generate assembly for a file
breezedecoration_automoc.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezedecoration_automoc.cpp.s
.PHONY : breezedecoration_automoc.cpp.s

breezeexceptionlist.o: breezeexceptionlist.cpp.o
.PHONY : breezeexceptionlist.o

# target to build an object file
breezeexceptionlist.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezeexceptionlist.cpp.o
.PHONY : breezeexceptionlist.cpp.o

breezeexceptionlist.i: breezeexceptionlist.cpp.i
.PHONY : breezeexceptionlist.i

# target to preprocess a source file
breezeexceptionlist.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezeexceptionlist.cpp.i
.PHONY : breezeexceptionlist.cpp.i

breezeexceptionlist.s: breezeexceptionlist.cpp.s
.PHONY : breezeexceptionlist.s

# target to generate assembly for a file
breezeexceptionlist.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezeexceptionlist.cpp.s
.PHONY : breezeexceptionlist.cpp.s

breezesettings.o: breezesettings.cpp.o
.PHONY : breezesettings.o

# target to build an object file
breezesettings.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettings.cpp.o
.PHONY : breezesettings.cpp.o

breezesettings.i: breezesettings.cpp.i
.PHONY : breezesettings.i

# target to preprocess a source file
breezesettings.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettings.cpp.i
.PHONY : breezesettings.cpp.i

breezesettings.s: breezesettings.cpp.s
.PHONY : breezesettings.s

# target to generate assembly for a file
breezesettings.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettings.cpp.s
.PHONY : breezesettings.cpp.s

breezesettingsprovider.o: breezesettingsprovider.cpp.o
.PHONY : breezesettingsprovider.o

# target to build an object file
breezesettingsprovider.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettingsprovider.cpp.o
.PHONY : breezesettingsprovider.cpp.o

breezesettingsprovider.i: breezesettingsprovider.cpp.i
.PHONY : breezesettingsprovider.i

# target to preprocess a source file
breezesettingsprovider.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettingsprovider.cpp.i
.PHONY : breezesettingsprovider.cpp.i

breezesettingsprovider.s: breezesettingsprovider.cpp.s
.PHONY : breezesettingsprovider.s

# target to generate assembly for a file
breezesettingsprovider.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesettingsprovider.cpp.s
.PHONY : breezesettingsprovider.cpp.s

breezesizegrip.o: breezesizegrip.cpp.o
.PHONY : breezesizegrip.o

# target to build an object file
breezesizegrip.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesizegrip.cpp.o
.PHONY : breezesizegrip.cpp.o

breezesizegrip.i: breezesizegrip.cpp.i
.PHONY : breezesizegrip.i

# target to preprocess a source file
breezesizegrip.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesizegrip.cpp.i
.PHONY : breezesizegrip.cpp.i

breezesizegrip.s: breezesizegrip.cpp.s
.PHONY : breezesizegrip.s

# target to generate assembly for a file
breezesizegrip.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/breezesizegrip.cpp.s
.PHONY : breezesizegrip.cpp.s

config/breezeconfigwidget.o: config/breezeconfigwidget.cpp.o
.PHONY : config/breezeconfigwidget.o

# target to build an object file
config/breezeconfigwidget.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeconfigwidget.cpp.o
.PHONY : config/breezeconfigwidget.cpp.o

config/breezeconfigwidget.i: config/breezeconfigwidget.cpp.i
.PHONY : config/breezeconfigwidget.i

# target to preprocess a source file
config/breezeconfigwidget.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeconfigwidget.cpp.i
.PHONY : config/breezeconfigwidget.cpp.i

config/breezeconfigwidget.s: config/breezeconfigwidget.cpp.s
.PHONY : config/breezeconfigwidget.s

# target to generate assembly for a file
config/breezeconfigwidget.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeconfigwidget.cpp.s
.PHONY : config/breezeconfigwidget.cpp.s

config/breezedetectwidget.o: config/breezedetectwidget.cpp.o
.PHONY : config/breezedetectwidget.o

# target to build an object file
config/breezedetectwidget.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezedetectwidget.cpp.o
.PHONY : config/breezedetectwidget.cpp.o

config/breezedetectwidget.i: config/breezedetectwidget.cpp.i
.PHONY : config/breezedetectwidget.i

# target to preprocess a source file
config/breezedetectwidget.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezedetectwidget.cpp.i
.PHONY : config/breezedetectwidget.cpp.i

config/breezedetectwidget.s: config/breezedetectwidget.cpp.s
.PHONY : config/breezedetectwidget.s

# target to generate assembly for a file
config/breezedetectwidget.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezedetectwidget.cpp.s
.PHONY : config/breezedetectwidget.cpp.s

config/breezeexceptiondialog.o: config/breezeexceptiondialog.cpp.o
.PHONY : config/breezeexceptiondialog.o

# target to build an object file
config/breezeexceptiondialog.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptiondialog.cpp.o
.PHONY : config/breezeexceptiondialog.cpp.o

config/breezeexceptiondialog.i: config/breezeexceptiondialog.cpp.i
.PHONY : config/breezeexceptiondialog.i

# target to preprocess a source file
config/breezeexceptiondialog.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptiondialog.cpp.i
.PHONY : config/breezeexceptiondialog.cpp.i

config/breezeexceptiondialog.s: config/breezeexceptiondialog.cpp.s
.PHONY : config/breezeexceptiondialog.s

# target to generate assembly for a file
config/breezeexceptiondialog.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptiondialog.cpp.s
.PHONY : config/breezeexceptiondialog.cpp.s

config/breezeexceptionlistwidget.o: config/breezeexceptionlistwidget.cpp.o
.PHONY : config/breezeexceptionlistwidget.o

# target to build an object file
config/breezeexceptionlistwidget.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionlistwidget.cpp.o
.PHONY : config/breezeexceptionlistwidget.cpp.o

config/breezeexceptionlistwidget.i: config/breezeexceptionlistwidget.cpp.i
.PHONY : config/breezeexceptionlistwidget.i

# target to preprocess a source file
config/breezeexceptionlistwidget.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionlistwidget.cpp.i
.PHONY : config/breezeexceptionlistwidget.cpp.i

config/breezeexceptionlistwidget.s: config/breezeexceptionlistwidget.cpp.s
.PHONY : config/breezeexceptionlistwidget.s

# target to generate assembly for a file
config/breezeexceptionlistwidget.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionlistwidget.cpp.s
.PHONY : config/breezeexceptionlistwidget.cpp.s

config/breezeexceptionmodel.o: config/breezeexceptionmodel.cpp.o
.PHONY : config/breezeexceptionmodel.o

# target to build an object file
config/breezeexceptionmodel.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionmodel.cpp.o
.PHONY : config/breezeexceptionmodel.cpp.o

config/breezeexceptionmodel.i: config/breezeexceptionmodel.cpp.i
.PHONY : config/breezeexceptionmodel.i

# target to preprocess a source file
config/breezeexceptionmodel.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionmodel.cpp.i
.PHONY : config/breezeexceptionmodel.cpp.i

config/breezeexceptionmodel.s: config/breezeexceptionmodel.cpp.s
.PHONY : config/breezeexceptionmodel.s

# target to generate assembly for a file
config/breezeexceptionmodel.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeexceptionmodel.cpp.s
.PHONY : config/breezeexceptionmodel.cpp.s

config/breezeitemmodel.o: config/breezeitemmodel.cpp.o
.PHONY : config/breezeitemmodel.o

# target to build an object file
config/breezeitemmodel.cpp.o:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeitemmodel.cpp.o
.PHONY : config/breezeitemmodel.cpp.o

config/breezeitemmodel.i: config/breezeitemmodel.cpp.i
.PHONY : config/breezeitemmodel.i

# target to preprocess a source file
config/breezeitemmodel.cpp.i:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeitemmodel.cpp.i
.PHONY : config/breezeitemmodel.cpp.i

config/breezeitemmodel.s: config/breezeitemmodel.cpp.s
.PHONY : config/breezeitemmodel.s

# target to generate assembly for a file
config/breezeitemmodel.cpp.s:
	cd /home/kver/Development/source/breeze && $(MAKE) -f kdecoration/CMakeFiles/breezedecoration.dir/build.make kdecoration/CMakeFiles/breezedecoration.dir/config/breezeitemmodel.cpp.s
.PHONY : config/breezeitemmodel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... breezedecoration"
	@echo "... breezedecoration_automoc"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... breezebutton.o"
	@echo "... breezebutton.i"
	@echo "... breezebutton.s"
	@echo "... breezecolorsettings.o"
	@echo "... breezecolorsettings.i"
	@echo "... breezecolorsettings.s"
	@echo "... breezedecoration.o"
	@echo "... breezedecoration.i"
	@echo "... breezedecoration.s"
	@echo "... breezedecoration_automoc.o"
	@echo "... breezedecoration_automoc.i"
	@echo "... breezedecoration_automoc.s"
	@echo "... breezeexceptionlist.o"
	@echo "... breezeexceptionlist.i"
	@echo "... breezeexceptionlist.s"
	@echo "... breezesettings.o"
	@echo "... breezesettings.i"
	@echo "... breezesettings.s"
	@echo "... breezesettingsprovider.o"
	@echo "... breezesettingsprovider.i"
	@echo "... breezesettingsprovider.s"
	@echo "... breezesizegrip.o"
	@echo "... breezesizegrip.i"
	@echo "... breezesizegrip.s"
	@echo "... config/breezeconfigwidget.o"
	@echo "... config/breezeconfigwidget.i"
	@echo "... config/breezeconfigwidget.s"
	@echo "... config/breezedetectwidget.o"
	@echo "... config/breezedetectwidget.i"
	@echo "... config/breezedetectwidget.s"
	@echo "... config/breezeexceptiondialog.o"
	@echo "... config/breezeexceptiondialog.i"
	@echo "... config/breezeexceptiondialog.s"
	@echo "... config/breezeexceptionlistwidget.o"
	@echo "... config/breezeexceptionlistwidget.i"
	@echo "... config/breezeexceptionlistwidget.s"
	@echo "... config/breezeexceptionmodel.o"
	@echo "... config/breezeexceptionmodel.i"
	@echo "... config/breezeexceptionmodel.s"
	@echo "... config/breezeitemmodel.o"
	@echo "... config/breezeitemmodel.i"
	@echo "... config/breezeitemmodel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/kver/Development/source/breeze && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

